on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Count words in files
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Word count
        uses: ./ # Uses an action in the root directory
        id: counter
        with:
          fileExtensions: ".py, .tex, .yml"
      - name: Get number of words
        run: echo "The number of words in spesified files was ${{ steps.counter.outputs.myOutput }}"
